[package]
name = "krata-xenstore"
description = "A client that interacts with xenstore for krata"
license.workspace = true
version.workspace = true
homepage.workspace = true
repository.workspace = true
edition = "2021"
resolver = "2"

[dependencies]
byteorder = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lib]
name = "xenstore"

[dev-dependencies]
env_logger = { workspace = true }

[[example]]
name = "xenstore-ls"
path = "examples/list.rs"

[[example]]
name = "xenstore-watch"
path = "examples/watch.rs"
